### PR TITLE
secure DOIs

### PR DESCRIPTION
**Pull request by katrinleinweber**
new suggested resolver, see https://www.doi.org/

### CODE REVIEW

**Comment by hlapp** [comment]
Looks like the relevant DOI documentation section is this: https://www.doi.org/doi_handbook/3_Resolution.html#3.7.3

The recommended URL prefix for the proxy server there is http://doi.org/ (not https). Although I'm a proponent of encryption everywhere, it's probably best not to deviate from the standards specification document.

**Comment by hlapp** [comment]
@dleehr can you check the Travis CI failures when you have time? It seems that they boil down to versions other than Ruby 2.0.0 failing (1.9.3 and 2.1 both fail). Perhaps we should just limit testing to 2.0.0 so the tests succeed? Or is there another easy fix?

**Comment by katrinleinweber** [comment]
HTTPs is mentioned in [3.8](https://www.doi.org/doi_handbook/3_Resolution.html#3.8), though ;-) Maybe neither version is "suggested" per se.

**Comment by hlapp** [comment]
> HTTPs is mentioned in 3.8, though ;-) Maybe neither version is "suggested" per se.

Indeed. The phrase is "_The proxy servers respond to HTTPS as well as HTTP requests._" So I suppose it's fair to interpret this as a commitment to support https as much as http.

**Comment by dleehr** [comment]
@katrinleinweber Thanks for the PR. Looks like we had some stale stuff in the Gemfile that caused the build to fail. I've updated master - do you mind merging in those changes so the build runs again?

**Comment by katrinleinweber** [comment]
I rebased `patch-1` & force-pushed. Here's to hoping :wine_glass:

**Pull request merged**
